### ISSUE TITLE
FirebaseInstanceId cannot be resolved to a type

### ISSUE THREAD

**Issue by achinverma** [dandar3/android-google-firebase-analytics#1]
Hi 
i am using this in eclipse for FCM but after adding in my project i am getting 
`FirebaseInstanceId cannot be resolved to a type`
`InstanceIDListenerService cannot be resolved to a type`
`FirebaseMessagingService cannot be resolved to a type`

I have added both below library in my project
android-google-play-services-basement 
android-google-play-services-tasks

please guide me ?

**Comment by dandar3** [comment]
Hi @achinverma,

If you google `FirebaseInstanceId` you can see it is part of the IID ('android-google-firebase-iid') package, which is a requisite for `android-google-firebase-analytics-impl`.

I know it's a bit complicated to go through all packages to see other required packages, that is why I wrote this overview page to show you which packages you need to take.
https://github.com/dandar3/android-google-firebase-README

Working on 9.6.1 to make it even easier to take entire projects sets in one go, will come back with details as soon as it's done.

Keep in mind that Eclipse is not supported, have had problems initializing Firebase even when following the Google Services Plugin, will try again with 9.6.1. If you have better luck yourself, please let us know.

**Comment by dandar3** [comment]
Alright, 9.6.1 is up.

See https://github.com/dandar3/android-google-firebase-README and especially the two videos at the end - the second one shows you an easier way of taking an entire project set in one go.

**Comment by dandar3** [comment]
Any luck, did you resolve your issue?

**Comment by achinverma** [comment]
not yet , but thanks for your reply, 
please can you share any demo of fcm with eclipse if you have created .
my email id is 
achinverma1990@gmail.com

**Comment by dandar3** [comment]
I'm preparing a workspace based on projects from https://github.com/firebase/quickstart-android and Google Play Services 9.8.0, will contact you soon.

**Comment by dandar3** [comment]
Success, yay!  👍 😃

Digging into it for the last couple of days found some of the things it needed to get a sucesful upload, now waiting for the next couple of hours to see the data in the console up on the web.

I will write a wiki or a blog post listing what needs to be done and will come back with it here.

**Comment by dandar3** [comment]
Success, yay! :-)

Digging into it for the last couple of days found some of the things it needed to get a sucesful upload, now waiting for the next couple of hours to see the data in the console up on the web.

I will write a wiki or a blog post listing what needs to be done and will come back with it here.

**Comment by dandar3** [comment]
Success, yay! :-)

Digging into it for the last couple of days found some of the things it needed to get a sucesful upload, now waiting for the next couple of hours to see the data in the console up on the web.

I will write a wiki or a blog post listing what needs to be done and will come back with it here.

**Comment by dandar3** [comment]
Read all the details here:
http://dandar3.blogspot.com/2016/11/eclipse-integrate-firebase-analytics.html

In short, it's all about:
- Following the `Processing the JSON file` section in the Google Services Gradle plugin documentation to bring the google-services.json configuration into your project - see  https://firebase.google.com/docs/reference/gradle/#processing_the_json_file
- Update AndroidManifest.xml to add all the permissions, receivers, service etc that the Gradle plugin would generate for you in Android Studio (`app\intermediates\manifests\full\debug\AndroidManifest.xml`).

**Comment by dandar3** [comment]
No response since, closing.

**Comment by tanmayrsm** [comment]
closing what ?
